version: 2.1
jobs:
  build:
    resource_class: medium
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: 
          name: clean cache
          command: npm cache clean --force
            
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run-script build

      - store_artifacts:
          path: build/static/
          destination: BuildResult

  deploy:
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: 
          name: git remote
          command: git remote -v

      - run:  
          name: git delete branch 
          command: git branch -D main
      - run: 
          name: git remote set-url 
          # command: git remote set-url heroku https://git.heroku.com/showlistproject.git git@heroku.com:showlistproject.git
          command: git remote add heroku https://git.heroku.com/showlistproject.git

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:a8f4f414-8b90-4f3a-aa4d-6dc7e35fceae@git.heroku.com/git.heroku.com/showlistproject.git main

workflows:
  version: 2.1
  workflow:
    jobs:
     - build
     - deploy:
        requires:
          - build



