version: 2.1
jobs:
  build:
    resource_class: medium
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: 
          name: clean cache
          command: npm cache clean --force
            
      - run:
          name: npm install
          command: npm install --save env-ci

      - run:
          name: build
          command: npm run-script build

      - store_artifacts:
          path: build/static/
          destination: BuildResult

  test:
    resource_class: medium
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run:
          name: install cypress
          command: npm install cypress --save-dev
      # - run:
      #     name: Install mocha
      #     command: npm i --D mocha mochawesome mochawesome-merge mochawesome-report-generator
      # - run:
      #     name: Create report
      #     command: npm run generate:html:report
      - run:
          name: Install
          command: |
            npm install --dev mocha
            npm install --dev mochawesome
            npm install --dev mochawesome-merge
      - run:
          name: list
          command: -ls -a
      # - run:
      #     name: Run project and Test
      #     command: |
      #       npm start & npx cypress run --spec "./cypress/integration/test_login.js"
      #       npm run generate:html:report

      # - run:
      #     name: run cypress
      #     command: npx cypress run --spec "./cypress/integration/test_login.js"
      # - store_artifacts:
      #     path: cypress/integration
      #     destination: TestResult
      # - store_artifacts:
      #     path: cypress/videos
      #     destination: TestVideoResult
      # - store_test_results:
      #     path: mochaawesome-report
      # - store_artifacts:
      #     path: mochaawesome-report
      # - store_artifacts:
      #     path: cypress/videos
      # - store_artifacts:
      #     path: cypress/videos

workflows:
  version: 2.1
  workflow:
    jobs:
    # - build
    - test
      # - deploy

