version: 2.1
jobs:
  build:
    resource_class: medium
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: 
          name: clean cache
          command: npm cache clean --force
            
      - run:
          name: npm install
          command: npm install --save env-ci

      - run:
          name: build
          command: npm run-script build

      - store_artifacts:
          path: build/static/
          destination: BuildResult

  test:
    resource_class: medium
    machine:   
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run:
          name: install cypress
          command: npm install cypress --save-dev
      - run:
          name: Run project and Test
          command: npm start & npx cypress run --spec "./cypress/integration/test_login.js"
      # - run:
      #     name: run cypress
      #     command: npx cypress run --spec "./cypress/integration/test_login.js"
      - store_artifacts:
          path: cypress/integration
          destination: TestResult
      - store_artifacts:
          path: cypress/videos
          destination: TestVideoResult

workflows:
  version: 2.1
  workflow:
    jobs:
    # - build
    - test
      # - deploy

